site_name: CommunityHoneyNetwork
site_url: https://communityhoneynetwork.github.io
repo_url: https://github.com/CommunityHoneyNetwork
site_description: An Open, Post-Modern Honey Network for OpSec Drop Bears, and the rest of us
theme: readthedocs
pages:
  - CommunityHoneyNetwork: index.md
  - QuickStart Guide: quickstart.md
  - Advanced Deployments: advanced.md
  - About:
      - License: LICENSE.md
