site_name: CommunityHoneyNetwork
site_url: https://communityhoneynetwork.readthedocs.io
theme: readthedocs
docs_dir: docs
markdown_extensions:
- markdown.extensions.admonition
pages:
    - 'CommunityHoneyNetwork': index.md
    - 'Prerequisites': prerequisite.md
    - 'CHN Server Install': serverinstall.md
    - 'Your First Honeypot': firstpot.md
    - 'Deploying More Honeypots': honeypots.md
    - 'Advanced Options':
        - 'Production & Security Considerations': prod_security.md
        - 'Upgrade Notes': upgrading.md
        - 'Advanced Configuration': config.md
        - 'Custom certificates': certificates.md
    - 'Getting Data':
        - 'CHN Server API': serverapi.md
        - 'Logfiles': hpfeeds-logger.md
        - 'CIF': hpfeeds-cif.md
        - 'CHN Intel Feeds': chnintelfeed.md
        - 'Blocking with BHR': hpfeeds-bhr.md
    - 'Honeypot Configuration Details':
        - 'Cowrie': cowrie.md
        - 'Dionaea': dionaea.md
        - 'Honeydb-agent': honeydb-agent.md
        - 'ssh-auth-logger': ssh-auth-logger.md
        - 'Conpot': conpot.md
        - 'RDPhoney': rdphoney.md
        - 'Elasticpot': elasticpot.md
        - 'Big-HP': big-hp.md
        - 'UHP': uhp.md
    - 'LICENSE': LICENSE.md
