site_name: CommunityHoneyNetwork
site_url: https://communityhoneynetwork.readthedocs.io
theme: readthedocs
docs_dir: docs
markdown_extensions:
- markdown.extensions.admonition
pages:
    - 'CommunityHoneyNetwork': index.md
    - 'QuickStart Guide': quickstart.md
    - 'Your First Honeypot': firstpot.md
    - 'Deploying More Honeypots': honeypots.md
    - 'Production & Security Considerations': prod_security.md
    - 'Advanced Options':
        - 'Advanced Configuration': config.md
        - 'Deploying without Docker': nondocker.md
        - 'Deploying on Kubernetes': kubernetes.md
        - 'Deploying to cloud providers': cloud.md
    - 'Honeypot Configuration Details':
        - 'Cowrie': cowrie.md
        - 'Dionaea': dionaea.md
        - 'Glastopf': glastopf.md
        - 'Wordpot': wordpot.md
        - 'Conpot': conpot.md
        - 'Amun': amun.md
        - 'RDPhoney': rdphoney.md
        - 'UHP': uhp.md
    - 'Getting Data':
      - 'CHN Server API': serverapi.md
      - 'CIF': hpfeeds-cif.md
      - 'Logfiles': hpfeeds-logger.md
    - 'LICENSE': LICENSE.md
