site_name: CommunityHoneyNetwork
site_url: https://communityhoneynetwork.github.io
repo_url: https://github.com/CommunityHoneyNetwork/docs
edit_uri: edit/master
site_description: An Open, Post-Modern Honey Network for OpSec Drop Bears, and the rest of us
google_analytics: ['UA-106435025-1', 'CommunityHoneyNetwork.github.io']
theme: readthedocs
pages:
  - CommunityHoneyNetwork: index.md
  - QuickStart Guide: quickstart.md
  - Your First Honeypot: firstpot.md
  - Advanced Options: 
    - Advanced Configuration: config.md
    - Deploying without Docker: nondocker.md
    - Deploying on Kubernetes: kubernetes.md
    - Deploying to cloud providers: cloud.md
  - Honeypots:
    - Cowrie: cowrie.md

    #  - About:
    #  - License: LICENSE.md
