site_name: CommunityHoneyNetwork
site_url: https://communityhoneynetwork.github.io
repo_url: https://github.com/CommunityHoneyNetwork/docs
edit_uri: edit/master
dev_addr: 0.0.0.0:8080
site_description: An Open, Post-Modern Honey Network for OpSec Drop Bears, and the rest of us
google_analytics: ['UA-106435025-1', 'CommunityHoneyNetwork.github.io']
theme: readthedocs
markdown_extensions:
  - markdown.extensions.admonition
pages:
  - CommunityHoneyNetwork: index.md
  - QuickStart Guide: quickstart.md
  - Your First Honeypot: firstpot.md
  - Security Considerations: security.md
  - Advanced Options: 
    - Advanced Configuration: config.md
    - Deploying without Docker: nondocker.md
    - Deploying on Kubernetes: kubernetes.md
    - Deploying to cloud providers: cloud.md
  - Honeypots:
    - Cowrie: cowrie.md
    - Dionaea: dionaea.md
    - Glastopf: glastopf.md
    - Wordpot: wordpot.md
    - Conpot: conpot.md
    - Amun: amun.md
    - RDPhoney: rdphoney.md
  - API:
    - CHN Server: serverapi.md

    #  - About:
    #  - License: LICENSE.md
